services:

  #PHP Service
  php5_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_USER_ID=${DOCKER_USER_ID}
    container_name: php5_app
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      APP_URL: http://localhost
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-env/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    expose:
      - 9000
      - 5173
    links:
      - php5_app_db
      - php5_app_phpmyadmin
    networks:
      - app
    # command: >
    #   sh -c "npm install && npm run dev & php-fpm"

  #Nginx Service
  php5_app_webserver:
    image: nginx:alpine
    container_name: php5_app_webserver
    tty: true
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./:/var/www
      - ./docker-env/nginx/conf.d/dev/:/etc/nginx/conf.d/
    links:
      - php5_app
    networks:
      - app

  #MySQL Service
  php5_app_db:
    image: mysql:8
    container_name: ${DB_HOST}
    tty: true
    expose:
      - "${DB_PORT}"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app

  php5_app_phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: app5_pma
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 20M
    ports:
      - "8080:80"
    networks:
      - app

# Volumes
volumes:
  dbdata:
    driver: local

networks:
  app:
